"use client";

import { useState } from "react";
import { useApp } from "@/context/AppContext";
import { User, Department } from "@/types";
import { Trash2, Plus, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { cn } from "@/lib/utils";

export function UserManagement() {
    const { users, departments, addUser, deleteUser, updateUser } = useApp();
    const [newUser, setNewUser] = useState<Partial<User>>({
        departmentId: "",
    });
    const [isEditing, setIsEditing] = useState(false);

    const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);

    const [error, setError] = useState<string | null>(null);

    const handleAddUser = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);

        if (!newUser.surname || !newUser.name || !newUser.departmentId || !newUser.startDate) {
            setError("Please fill in all required fields (Surname, Name, Department, Start Date).");
            return;
        }

        try {
            if (isEditing && newUser.id) {
                const updateData: Partial<User> = {
                    id: newUser.id,
                    am: newUser.am, // Keep existing AM
                    surname: newUser.surname,
                    name: newUser.name,
                    departmentId: newUser.departmentId,
                    startDate: newUser.startDate,
                    endDate: newUser.endDate,
                    username: newUser.username,
                    isAdmin: newUser.isAdmin,
                };
                // Only send password if it has been changed (non-empty)
                if (newUser.password) {
                    updateData.password = newUser.password;
                }
                await updateUser(updateData);
                setIsEditing(false);
            } else {
                await addUser({
                    // am is generated by server
                    surname: newUser.surname,
                    name: newUser.name,
                    departmentId: newUser.departmentId,
                    startDate: newUser.startDate,
                    endDate: newUser.endDate,
                    username: newUser.username,
                    password: newUser.password,
                    isAdmin: newUser.isAdmin,
                });
            }
            setNewUser({ departmentId: "", am: "", surname: "", name: "", startDate: "", endDate: "" });
        } catch (err: any) {
            console.error("Failed to save user:", err);
            setError(err.message || "Failed to save user. Please try again.");
        }
    };

    const handleEditClick = (user: User) => {
        setNewUser({
            id: user.id,
            am: user.am,
            surname: user.surname,
            name: user.name,
            departmentId: user.departmentId,
            startDate: user.startDate,
            endDate: user.endDate,
            username: user.username,
            isAdmin: user.isAdmin,
            // Do not pre-fill password to allow "leave blank to keep" logic
            password: "",
        });
        setIsEditing(true);
    };

    const handleCancelEdit = () => {
        setNewUser({ departmentId: "", am: "", surname: "", name: "", startDate: "", endDate: "" });
        setIsEditing(false);
    };

    const confirmDelete = async () => {
        if (deleteConfirmId) {
            await deleteUser(deleteConfirmId);
            setDeleteConfirmId(null);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center gap-4">
                <Link href="/admin" className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                    <ArrowLeft className="h-5 w-5 text-gray-600" />
                </Link>
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">User Management</h1>
                    <p className="text-gray-500">Add and manage employees.</p>
                </div>
            </div>

            <div className="bg-white p-6 rounded-lg shadow-sm border">
                <h2 className="text-lg font-semibold text-gray-800 mb-4">
                    {isEditing ? "Edit Employee" : "Add New Employee"}
                </h2>
                {error && (
                    <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
                        <span className="block sm:inline">{error}</span>
                    </div>
                )}
                <form onSubmit={handleAddUser} className="space-y-6">
                    {/* Personal & Job Details */}
                    <div>
                        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Surname</label>
                                <input
                                    type="text"
                                    required
                                    value={newUser.surname || ""}
                                    onChange={(e) => setNewUser({ ...newUser, surname: e.target.value })}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 border p-2"
                                    placeholder="Surname"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Name</label>
                                <input
                                    type="text"
                                    required
                                    value={newUser.name || ""}
                                    onChange={(e) => setNewUser({ ...newUser, name: e.target.value })}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 border p-2"
                                    placeholder="Name"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Department</label>
                                <select
                                    value={newUser.departmentId}
                                    onChange={(e) => setNewUser({ ...newUser, departmentId: e.target.value })}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 border p-2"
                                    required
                                >
                                    <option value="">Select Dept</option>
                                    {departments.map((dept) => (
                                        <option key={dept.id} value={dept.id}>
                                            {dept.name}
                                        </option>
                                    ))}
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                                <input
                                    type="date"
                                    required
                                    value={newUser.startDate ? newUser.startDate.split('T')[0] : ""}
                                    onChange={(e) => setNewUser({ ...newUser, startDate: e.target.value })}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 border p-2"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">End Date</label>
                                <input
                                    type="date"
                                    value={newUser.endDate ? newUser.endDate.split('T')[0] : ""}
                                    onChange={(e) => setNewUser({ ...newUser, endDate: e.target.value })}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 border p-2"
                                />
                            </div>
                        </div>
                    </div>

                    {/* Account Credentials */}
                    <div>
                        <h3 className="text-sm font-medium text-gray-500 mb-3 uppercase tracking-wider border-t pt-4">Account Credentials</h3>
                        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                            {isEditing && (
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">ID</label>
                                    <input
                                        type="text"
                                        required
                                        disabled
                                        value={newUser.am || ""}
                                        className="w-full rounded-md border-gray-300 shadow-sm bg-gray-100 text-gray-500 cursor-not-allowed border p-2"
                                    />
                                </div>
                            )}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Username</label>
                                <input
                                    type="text"
                                    value={newUser.username || ""}
                                    onChange={(e) => setNewUser({ ...newUser, username: e.target.value })}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 border p-2"
                                    placeholder="Username"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                                <input
                                    type="text"
                                    value={newUser.password || ""}
                                    onChange={(e) => setNewUser({ ...newUser, password: e.target.value })}
                                    className="w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 border p-2"
                                    placeholder={isEditing ? "(Leave blank to keep)" : "Password"}
                                />
                            </div>
                            <div className="flex items-center gap-4 h-10 pb-2">
                                <label className="flex items-center gap-2 cursor-pointer">
                                    <input
                                        type="checkbox"
                                        checked={newUser.isAdmin || false}
                                        onChange={(e) => setNewUser({ ...newUser, isAdmin: e.target.checked })}
                                        className="rounded border-gray-300 text-blue-600 shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                    />
                                    <span className="text-sm font-medium text-gray-700">Is Admin</span>
                                </label>

                                <div className="flex gap-2 ml-4">
                                    <button
                                        type="submit"
                                        className="flex items-center justify-center gap-1 bg-blue-600 text-white px-3 py-1.5 text-sm rounded-md hover:bg-blue-700 transition-colors"
                                    >
                                        {isEditing ? "Update" : <><Plus className="h-3 w-3" /> Add</>}
                                    </button>
                                    {isEditing && (
                                        <button
                                            type="button"
                                            onClick={handleCancelEdit}
                                            className="px-3 py-1.5 text-sm border border-gray-300 rounded-md hover:bg-gray-50 text-gray-700"
                                        >
                                            Cancel
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div className="bg-white rounded-lg shadow-sm border overflow-hidden">
                <table className="w-full text-sm text-left">
                    <thead className="bg-gray-50 text-gray-700 font-medium border-b">
                        <tr>
                            <th className="p-4">ID</th>
                            <th className="p-4">Surname</th>
                            <th className="p-4">Name</th>
                            <th className="p-4">Username</th>
                            <th className="p-4">Department</th>
                            <th className="p-4">Role</th>
                            <th className="p-4">Start Date</th>
                            <th className="p-4">End Date</th>
                            <th className="p-4 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y">
                        {users.map((user) => (
                            <tr key={user.id} className="hover:bg-gray-50">
                                <td className="p-4 font-medium">{user.am}</td>
                                <td className="p-4">{user.surname}</td>
                                <td className="p-4">{user.name}</td>
                                <td className="p-4 text-gray-600">{user.username}</td>
                                <td className="p-4">{user.department?.name}</td>
                                <td className="p-4">
                                    {user.isAdmin ? (
                                        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-700">
                                            Admin
                                        </span>
                                    ) : (
                                        <span className="text-gray-500">User</span>
                                    )}
                                </td>
                                <td className="p-4 text-gray-600">
                                    {user.startDate ? new Date(user.startDate).toLocaleDateString() : "-"}
                                </td>
                                <td className="p-4 text-gray-600">
                                    {user.endDate ? new Date(user.endDate).toLocaleDateString() : "-"}
                                </td>
                                <td className="p-4 text-right">
                                    <div className="flex justify-end gap-2">
                                        <button
                                            onClick={() => handleEditClick(user)}
                                            className="text-blue-600 hover:text-blue-800 p-2 hover:bg-blue-50 rounded-full transition-colors"
                                        >
                                            Edit
                                        </button>
                                        <button
                                            onClick={() => setDeleteConfirmId(user.id)}
                                            className="text-red-600 hover:text-red-800 p-2 hover:bg-red-50 rounded-full transition-colors"
                                        >
                                            <Trash2 className="h-4 w-4" />
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                        {users.length === 0 && (
                            <tr>
                                <td colSpan={9} className="p-8 text-center text-gray-500">
                                    No users found. Add one above.
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>

            {/* Confirmation Modal */}
            {deleteConfirmId && (
                <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
                    <div className="bg-white p-6 rounded-lg shadow-xl max-w-sm w-full mx-4">
                        <h3 className="text-lg font-bold text-gray-900 mb-2">Confirm Deletion</h3>
                        <p className="text-gray-600 mb-6">
                            Are you sure you want to delete this employee? This action cannot be undone.
                        </p>
                        <div className="flex justify-end gap-3">
                            <button
                                onClick={() => setDeleteConfirmId(null)}
                                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md transition-colors"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={confirmDelete}
                                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 transition-colors"
                            >
                                Delete
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
